api_platform:
    resource: .
    type: api_platform
    prefix: /api

get_user_mail:
    path: '/api/{id}/mail'
    controller: 'App\Controller\GetMailController::getUserMail'
    methods: [GET]

get_parking_like:
    path: '/api/parking/{id}'
    controller: 'App\Controller\GetParkingController::getUserParking'
    methods: [GET]

register:
    path: '/api/register'
    controller: 'App\Controller\RegisterController::register'
    methods: [POST]

setParkLike:
    path: '/api/setparklike/{id}'
    controller: 'App\Controller\SetParkLike::addUserParking'
    methods: [POST]

setToken:
    path: '/api/setToken/{id}'
    controller: 'App\Controller\SetTokenController::setToken'
    methods: [POST]

getIdToken:
    path: '/api/getIdToken'
    controller: 'App\Controller\GetUserIdControllerByToken::getUserId'
    methods: [POST]

changeMail:
    path: '/api/changemail/{id}'
    controller: 'App\Controller\ChangeMailController::changeUserMail'
    methods: [PUT]

DeleteUser:
    path: '/api/delete/{id}'
    controller: 'App\Controller\DeleteUserController::deleteUser'
    methods: [DELETE]

getIdMail:
    path: '/api/getIdMail'
    controller: 'App\Controller\GetUserIdControllerByMail::getUserId'
    methods: [POST]

connect:
    path: '/api/connect'
    controller: 'App\Controller\ConnectController::connect'
    methods: [POST]