api_platform:
    resource: .
    type: api_platform
    prefix: /api

get_parking_like:
    path: '/api/parking'
    controller: 'App\Controller\GetParkingController::getUserParking'
    methods: [GET]

register:
    path: '/api/register'
    controller: 'App\Controller\RegisterController::register'
    methods: [POST]

setParkLike:
    path: '/api/setparklike'
    controller: 'App\Controller\SetParkLike::addUserParking'
    methods: [POST]

deleteToken:
    path: '/api/deleteToken'
    controller: 'App\Controller\DeleteTokenController::deleteToken'
    methods: [POST]

changeMail:
    path: '/api/changemail'
    controller: 'App\Controller\ChangeMailController::changeUserMail'
    methods: [PUT]

DeleteUser:
    path: '/api/deleteUser'
    controller: 'App\Controller\DeleteUserController::deleteUser'
    methods: [DELETE]

connect:
    path: '/api/connect'
    controller: 'App\Controller\ConnectController::connect'
    methods: [POST]

checkToken:
    path: '/api/checkToken'
    controller: 'App\Controller\CheckTokenController::checkToken'
    methods: [POST]

send_Mail:
    path: '/api/sendMail'
    controller: 'App\Controller\SendMailController::sendMail'
    methods: [POST]